package com.hedvig.personservice.debts.model

enum class PaymentDefaultType(val text: String) {
    KK ("Konkurs"),
    SM ("Mervärdesskatt"),
    TD ("Tredskodom"),
    US ("Misslyckat utmätningsförsök"),
    ÅT ("Återtagning avbetalt gods"),
    SF ("Vägtrafikskatt"),
    SI ("F-skatt"),
    SX ("Arbetsgivaravgift"),
    KA ("Konkursansökan"),
    LU ("Lagsökningsutslag"),
    SP ("Punktskatter"),
    UH ("Utslag i hyresmål"),
    VP ("Växelprotest"),
    AB ("Ansökan betalning föreläggande"),
    SJ ("Särskild A-skatt"),
    SY ("Källskatt"),
    ST ("Tillkommande skatt"),
    KF ("Fattigkonkurs"),
    NF ("Näringsförbud"),
    SU ("Samordnad uppbörd"),
    UM ("Misslyckat utmätningsförsök"),
    ÅF ("Återtagningsförsök"),
    SR ("Kvarstående skatt"),
    SA ("Arbetsgivaravgift"),
    SN ("Särskild A-skatt"),
    AC ("Ackord"),
    AH ("Avhysning"),
    BF ("Utslag betalningsföreläggande"),
    DI ("Tidigare anmärkning dementeras"),
    SK ("Skattekonto"),
    SL ("Studiemedelsavgift"),
    IS ("Skuldsanering inledd"),
    BS ("Skuldsanering beslutad"),
    KS ("Avslutad konkurs"),
    FR ("Företagsrekonstruktion"),
    RA ("Redaravgift"),
    TU ("Tull och införselavgift"),
    KU ("Kupongskatt"),
    SG ("Gåvoskatt"),
    SH ("Arvsskatt"),
    MF ("Försäljningsskatt motorfordon"),
    AO ("Överlastavgift"),
    AD ("Sanktionsavgift för dieselolja"),
    AF ("Förseningsavgift enligt ABL"),
    AG ("Byggnadsavgift"),
    AS ("Särskild avgift enligt ABL"),
    AT ("Tilläggsavg olovligt byggande"),
    EB ("Ekonomiskt bistånd"),
    FO ("Diverse övriga fordringar"),
    FP ("Felparkeringsavgift"),
    FS ("Diverse statliga fordringar"),
    KL ("Kostnader lantmäteriförrättning"),
    SS ("Stämpelskatt"),
    TV ("TV-avgift"),
    UN ("Underhållsstöd"),
    SC ("Särsk inkomstskatt (utomlands)"),
    AV ("Vägavgift"),
    SE ("Trängselskatt"),
    EU ("Sociala avgifter EU"),
    AI ("Övrigt (ad interim)")
}
